export const fonts = {
    'regular': 'Poppins-Regular',
    'bold': 'Poppins-Bold',
    'light': 'Poppins-Light',
    'medium': 'Poppins-Medium',
    'semibold': 'Poppins-SemiBold',
    'thin': 'Poppins-Thin',
    'extralight': 'Poppins-ExtraLight',
    'black': 'Poppins-Black',
    'extrabold': 'Poppins-ExtraBold',
    'italic': 'Poppins-Italic',
    'lightitalic': 'Poppins-LightItalic',
    'mediumitalic': 'Poppins-MediumItalic',
    'semibolditalic': 'Poppins-SemiBoldItalic',
    'thinitalic': 'Poppins-ThinItalic',
    'extralightitalic': 'Poppins-ExtraLightItalic',
    'blackitalic': 'Poppins-BlackItalic',
    'extrabolditalic': 'Poppins-ExtraBoldItalic',
    'bolditalic': 'Poppins-BoldItalic',
}